on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Test locally with act
    steps:
      - name: Dry run action
        uses: ./
        with:
          openapi-file: https://kopfsachen-dev.github.io/api/openapi.yaml
